### ISSUE TITLE
Modified login page

### ISSUE THREAD

**Issue by ananyaa07** [shankarlohar/Hacktober-Fests#164]
@shankarlohar I have modified the login in page, please merge

![image](https://user-images.githubusercontent.com/97439364/197323673-52c2364d-a179-4d43-8b80-afddc16fd5c2.png)

**Comment by shankarlohar** [comment]
> @shankarlohar I have modified the login in page, please merge
> 
> ![image](https://user-images.githubusercontent.com/97439364/197323673-52c2364d-a179-4d43-8b80-afddc16fd5c2.png)
> 

Mention your issues when giving a pull request. 😔
