### ISSUE TITLE
Video embedded fix

### ISSUE THREAD

**Issue by ShankarLohar** [ShankarLohar/Hacktober-Fests#22]
Shift the video embed to the top of the page and shift the cards group below it.

**Comment by rohinirai010** [comment]
Please assign me this issue.

**Comment by ShankarLohar** [comment]
@rohinirai010 let me know if you need any help.

**Comment by rohinirai010** [comment]
> @rohinirai010 let me know if you need any help.
Thank you for assigning me this issue.
I just have to interchange the video and the cards groups right?

**Comment by ShankarLohar** [comment]
You probably have to make 2 divs. Feel free to do anything. Have fun!

**Comment by rohinirai010** [comment]
> You probably have to make 2 divs. Feel free to do anything. Have fun!

Okay.
