### ISSUE TITLE
make "LEARNING GIT AND GITHUB" move

### ISSUE THREAD

**Issue by ShankarLohar** [ShankarLohar/Hacktober-Fests#31]
animate the text to move left and right

**Comment by piyush-mahajan** [comment]
@ShankarLohar can you please assign me this issue? I would love to work on this project. I can use CSS properties for making text animation.

**Comment by ShankarLohar** [comment]
> @ShankarLohar can you please assign me this issue? I would love to work on this project. I can use CSS properties for making text animation. 

CSS 👑 huh? Nice to see you Piyush 😊
