### ISSUE TITLE
Fix 405 Not Allowed

### ISSUE THREAD

**Issue by ShankarLohar** [ShankarLohar/Hacktober-Fests#55]
Fix the HTTP error while switching the page to login screen.

**Comment by Ayushhgupta39** [comment]
Please assign me this issue.

**Comment by ShankarLohar** [comment]
Hey @Ayushhgupta39, your last commit didn't solve the issue. Please try something else. It still gave 405. and please use #<issuereferences> form your next pull requests!
Thank you.

**Comment by Ayushhgupta39** [comment]
@ShankarLohar Okay Sure! I'll try something else and if it works out, I'll again raise a PR. Thank you so much!
